services:
  api:
    image: ghcr.io/aliguilleng/go-api:latest
    container_name: devops-api
    restart: unless-stopped
    expose:
      - "8080"
    networks:
      devops-net:
        aliases:
          - api

  nginx:
    image: nginx:alpine
    container_name: devops-nginx
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - api
    networks:
      - devops-net

networks:
  devops-net:
    driver: bridge
